p <- read.table("prot.dat",header=T)
png("plot_two.png")
ymin <- min(p$A, p$B)
ymax <- max(p$A, p$B)
mA <- mean(p$A)
mB <- mean(p$B)
title <- sprintf("Mean A=%4.2f Mean B=%4.2f\n",mA,mB)
plot(p$A~p$T, type="l", ylim=c(ymin,ymax),main=title,ylab="RMS",xlab="Time") 
lines(p$B~p$T, col=2)
x<-dev.off()

